# Generated by Django 5.2.7 on 2025-10-28 10:52

import django.core.validators
import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('location', 'location'), ('achat', 'achat')], max_length=10)),
                ('property_type', models.CharField(choices=[('maison', 'maison'), ('villa', 'villa'), ('appartement', 'appartement'), ('bureau', 'bureau'), ('boutique', 'boutique'), ('terrain', 'terrain')], max_length=15)),
                ('location', models.CharField(max_length=100)),
                ('surface_area', models.PositiveSmallIntegerField(help_text="L'aire de la surface (en m²) doit être strictement supérieure à 0.", validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.PositiveIntegerField(help_text="Le prix d'un bien doit être strictement supérieur à 0.", validators=[django.core.validators.MinValueValidator(1)])),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Logement',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data_real_estate.property')),
                ('nb_bedrooms', models.PositiveSmallIntegerField(help_text='Le nombre de chambres doit être strictement supérieur à 0.', validators=[django.core.validators.MinValueValidator(1)])),
                ('nb_bathrooms', models.PositiveSmallIntegerField(help_text='Le nombre de douches doit être strictement supérieur à 0.', validators=[django.core.validators.MinValueValidator(1)])),
                ('has_parking', models.BooleanField()),
                ('is_furnished', models.BooleanField()),
            ],
            bases=('data_real_estate.property',),
        ),
        migrations.CreateModel(
            name='Professionel',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data_real_estate.property')),
                ('nb_rooms', models.PositiveSmallIntegerField(help_text='Le nombre de pièces doit être strictement supérieur à 0.', validators=[django.core.validators.MinValueValidator(1)])),
                ('nb_bathrooms', models.PositiveSmallIntegerField(help_text='Le nombre de douches doit être strictement supérieur à 0.', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_furnished', models.BooleanField()),
            ],
            bases=('data_real_estate.property',),
        ),
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data_real_estate.property')),
            ],
            bases=('data_real_estate.property',),
        ),
    ]
