# Generated by Django 5.2.8 on 2025-11-14 08:20

import django.core.validators
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('location', 'location'), ('achat', 'achat')], max_length=10)),
                ('property_type', models.CharField(choices=[('maison', 'maison'), ('villa', 'villa'), ('appartement', 'appartement'), ('bureau', 'bureau'), ('boutique', 'boutique'), ('terrain', 'terrain')], max_length=15)),
                ('price', models.PositiveIntegerField(help_text="Le prix d'un bien doit être strictement supérieur à 0.", validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(max_length=500)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True)),
            ],
        ),
    ]
