# Generated by Django 5.2.8 on 2025-11-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_real_estate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(default='Cotonou', max_length=200),
            preserve_default=False,
        ),
    ]
