# Generated by Django 5.2.7 on 2025-10-29 09:00

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_real_estate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True),
        ),
    ]
