# Generated by Django 5.2.8 on 2025-11-14 09:48

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_real_estate', '0002_property_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
