# Generated by Django 5.2.7 on 2025-11-10 10:43

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_real_estate', '0007_alter_property_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True),
        ),
    ]
