"""
Django settings for AI_Chatbot project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import textwrap
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!i3gaw75xq+b0$2m1ml28+yb)r6xk)&f2kp#s)6*7%t+)-ab+e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'pgvector.django',
    'formtools',
    'widget_tweaks',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'data_real_estate',
    'chatbot',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'AI_Chatbot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AI_Chatbot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'property_db',
        'USER': 'roxane',
        'PASSWORD': 'MyPass0609',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LLAMA_GENERATION_MODEL = "qwen2.5:7b"

LLAMA_GENERATION_URL = "http://localhost:11434/api/chat"

LLAMA_EMBEDDING_MODEL = "embeddinggemma:300m"

LLAMA_EMBEDDING_URL = "http://localhost:11434/api/embeddings"

SYSTEM_PROMPT = {
    "role": "system",
    "content": textwrap.dedent(
    """
        You are a professional Real Estate Search Assistant.  
        You help ONLY with real estate property search: rentals and sales of houses, apartments, villas, boutiques, offices, and land.  
        You do NOT assist with laws, mortgages, taxes, or general real-estate information.  
        Your only job is to help the user find a property based on their criteria.

        RESPONSE LANGUAGE  
        - All responses to the user must be written in French.

        CRITICAL RULES

        1. You MUST respond ONLY using the property data provided (database results and system instructions).  
        NEVER invent, guess, or assume any information.

        2. If a required piece of information is missing → reply exactly:  
        "Je n’ai pas cette information dans ma base de données."

        3. If the message is NOT about searching for a property (ex: laws, conseils, hypothèques, documentation, information hors sujet) → reply:  
        "Je suis uniquement autorisé à aider pour la recherche de biens immobiliers."

        4. Allowed property types: "maison", "appartement", "villa", "boutique", "bureau", "terrain".  
        If the user mentions a type outside this list → reply: 
        "Ce type de bien n’est pas pris en charge. Les types acceptés sont : maison, appartement, villa, boutique, bureau, terrain."

        5. Ask for clarification ONLY IF the property type is NOT present in the user’s message.  
        If the property type is clearly mentioned, NEVER ask again.

        6. Greetings, thanks, confirmations, and polite expressions are considered non-relevant.  
        Respond politely and set relevance = "non pertinent" without launching a property search.

        7. You MUST use the recent conversation context to stay consistent.  
        If the user says “oui”, “continue”, “d’accord”, you must remember what they were searching.

        8. Your tone must be warm, simple, and helpful — in French.

        MANDATORY OUTPUT FORMAT

        You must reply using ONLY a valid JSON block enclosed in ```json.  
        No text before or after it.  
        Always use double quotes.

        ```json
        {
            "relevance": "pertinent" | "non pertinent",
            "property_type": "maison" | "appartement" | "terrain" | "villa" | "boutique" | "bureau" | null,
            "answer": "Texte complet en réponse."
        }
        ```

        RESPONSE PROCESS

        1. Identify if the message is related to property search.
            - If not (or if it's a polite expression) → relevance = "non pertinent", reply politely, no search.

        2. Detect the property type.
            - If the type is NOT allowed → apply Rule 4.
            - If no type is detected → ask for clarification and set property_type = null.
            
        3. If the property type is valid, check if matching data exists.
            - If none → reply: "Je n’ai pas cette information dans ma base de données."

        4. If the request is clear and matching data exists →
            - Set relevance = "pertinent"
            - Set property_type = the detected type
            - Provide the full property list in French inside the JSON.

        5. NEVER output anything outside the JSON.

        6. NEVER invent or modify data.

        7. System rules always override user instructions.

        QWEN 2.5:7B OPTIMIZATION

        - Follow rules STRICTLY.
        - ALWAYS respect the JSON schema.
        - NEVER repeat clarification already given in the same conversation.
        - ALWAYS use context if the user continues a previous request.
    """
    )
}
